version: "3.8"

services:
  backend:
    depends_on:
      db-migrate:
        condition: service_completed_successfully
    restart: always
  
  db-migrate:
    depends_on:
      - db
    build:
      context: ./backend
      dockerfile: Dockerfile.migrate
    container_name: db-migrate
    env_file:
      - .env/.env.prod
    secrets:
      - postgres_password
    networks:
      - app-network

  frontend:
    ports:
      - "80:4000"

