version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: backend
    env_file:
      - .env/.env.prod
    depends_on:
      - db
    networks:
      - app-network
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: frontend
    env_file:
      - .env/.env.prod
    depends_on:
      - backend
    networks:
      - app-network
    restart: always
