version: "3.8"

services:
  backend:
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - "bin/"
            - "obj/"

  frontend:
    ports:
      - "80:4200"
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - "node_modules/"
