version: "3.8"

services:
  db:
    ports:
      - 5432:5432
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    env_file:
      - .env/.env.dev
    ports:
      - 8080:8080
    depends_on:
      - db
    secrets:
      - postgres_password
    networks:
      - app-network
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - "bin/"
            - "obj/"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    env_file:
      - .env/.env.dev
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - app-network
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - "node_modules/"
