version: "3.8"

services:
  backend:
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - "bin/"
            - "obj/"

#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile.dev
#    container_name: frontend
#    env_file:
#      - .env/.env.dev
#    ports:
#      - "4200:4200"
#    depends_on:
#      - backend
#    networks:
#      - app-network
#    develop:
#      watch:
#        - action: sync
#          path: ./frontend
#          target: /app
#          ignore:
#            - "node_modules/"
