FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /app
COPY . .
RUN apt-get update \
    && apt-get install -y unzip \
    && mkdir -p /root/.vsdbg \
    && curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /root/.vsdbg
RUN dotnet tool install --global dotnet-ef
CMD ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:8080", "--environment", "Development", "--project", "Application/Application.csproj", "--non-interactive"]
