FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /app
COPY . .
RUN dotnet tool install --global dotnet-ef
CMD ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:8080", "--environment", "Development", "--project", "Presentation/Presentation.csproj", "--non-interactive"]
