name: Deploy and Run Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 🚀 Execute remote script via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd /var/www/fluffy-friends
            git checkout main
            git pull https://quaqqva:${{ secrets.GITHUB_TOKEN }}@github.com/quaqqva/fluffy-friends.git main
            sudo bash ./scripts/docker-run.sh prod

