name: Deploy and Run Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Execute remote script via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [ -d "/var/www/flufy-friends" ]; then
              echo "📂 Папка существует, обновляю репозиторий..."
              cd /var/www/flufy-friends
              git checkout main
              git pull origin main
            else
              echo "📂 Папка не существует, клонирую репозиторий..."
              git clone -b main git clone https://quaqqva:${GITHUB_TOKEN}@github.com/quaqqva/fluffy-friends.git /var/www/flufy-friends /var/www/flufy-friends
              cd /var/www/flufy-friends
            fi
            sudo bash ./scripts/docker-run.sh prod
            sudo bash ./scripts/docker-migrate.sh

